### ISSUE TITLE
Get ERA-5 and NCEP data

### ISSUE THREAD

**Issue by kkkarnav** [kkkarnav/thesis#1]
- Divij has ERA-5 Reanalysis data on HPC. Get creds from him and scp it to our account.
 - Divij has a link to NCEP data. This is the numerical weather data recommended by Meghna. Download it.

**Comment by kkkarnav** [comment]
Grabbed ERA-5 Reanalysis data as .nc files from Divij

**Comment by SaptarishiD** [comment]
Downloaded 4x Daily Global NCEP tmax data from [here](https://downloads.psl.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/) and India subsetted daily tmax data from [here](https://psl.noaa.gov/mddb2/makePlot.html?variableID=138636). Will explore more combinations after working with the netCDF data for a bit.
